---
name: Build Code 
description: Build code and run checks
inputs:
  ref:
    description: Ref to checkout
    required: false
  debugging:
    description: Include debug
    default: "false"
    required: false

runs:
  using: composite
  steps:
    - name: Dump context for debugging
      if: ${{ inputs.debug == "true" }}
      run: |
        echo "$GITHUB_CONTEXT"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}

    - name: Dump JWT for debugging
      if: ${{ inputs.debug == "true" }}
      run: |
        IDTOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com"|jq -r ".|.value")
        # echo $IDTOKEN
        dump() {
            if [[ -x $(command -v jq) ]]; then
                jq -R 'split(".") | .[0],.[1] | @base64d | fromjson' <<< "${1}"
                echo "Signature: $(echo "${1}" | awk -F'.' '{print $3}')"
            fi
        }
        dump $IDTOKEN
        
    - name: Checkout code from ref
      if: ${{ inputs.ref }}
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.ref }}

    - name: Checkout code from workflow ref
      if: ${{ ! inputs.ref }}
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies with audit
      run: |
        npm ci
        npm audit check --omit=dev --audit-level=high
        npm run lint
        npm run build

    - name: Run tests
      run: npm run test

    

    