env:
  node: true
  es6: true
  jest: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  # Node16 100% 2021 (see https://node.green/)
  ecmaVersion: 2021
  sourceType: module
  # Needed for rules that require type information
  project: ./tsconfig.json

root: true
plugins:
  - '@typescript-eslint'
  - prettier
rules:
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
      avoidEscape: true
  no-useless-return:
    - warn
  '@typescript-eslint/no-unused-vars':
    - warn
    - vars: all
      args: after-used
      ignoreRestSiblings: true
      argsIgnorePattern: ^_
  semi:
    - error
    - never
  '@typescript-eslint/member-delimiter-style':
    - error
    - multiline:
        delimiter: none
        requireLast: false
      singleline:
        delimiter: comma
        requireLast: true
  '@typescript-eslint/no-this-alias':
    - error
    - allowDestructuring: true
      allowedNames:
        - self
  '@typescript-eslint/require-await':
    - warn
  '@typescript-eslint/no-floating-promises':
    - warn
  
