---
apiVersion: v1
kind: Service
metadata:
  name: otel-hello
spec:
  selector:
    app: otel-hello
  ports:
   -  name: http-web
      protocol: TCP
      port: 8080
      targetPort: http-web
   -  name: metrics
      protocol: TCP
      port: 9464
      targetPort: metrics


