---
name: Publish Docs
description: Publish documentation for Backstage
inputs:
  aws-region: 
    description: AWS region
    default: us-west-2
    required: false
  role-to-assume:
    description: IAM role to assume
    #default: SHARED_ROLE
    required: false
  bucket:
    description: S3 bucket name
    default: SHARED_BUCKET
    required: false

runs:
  using: composite
  steps:
    # https://backstage.io/docs/features/techdocs/configuring-ci-cd
    - name: Setup techdocs
      run: |
        npm install -g @techdocs/cli
        pip install mkdocs-techdocs-core==1.*

    # https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.3/tap/GUID-tap-gui-techdocs-usage.html
    - name: Generate docs
      run: |
        techdocs-cli generate --no-docker

    - name: Configure AWS credentials for S3 publish
      uses: aws-actions/configure-aws-credentials@v2
      with: ${{ inputs }}
        # role-to-assume: ${{ inputs.role-to-assume }}
        # aws-region: ${{ inputs.aws-region }}
    
    #https://github.com/backstage/backstage/discussions/17011
    - name: Publish docs to S3
      run: |
        techdocs-cli publish --publisher-type awsS3 \
          --storage-name ${{ inputs.bucket }} \
          --directory foo \ --entity <Namespace/Kind/Name>

      