---
name: Build and Push Image 
description: Build and Push docker images to GHCR
inputs:
  labels: 
    description: labels (string of name-value pairs)
    required: false 
  github-token:
    description: github token
    required: true
  github-repo:
    description: github repo
    default: ghcr.io
    required: false
  dockerfile:
    description: Dockerfile path
    default: docker/Dockerfile
    required: false
  context:
    description: >-
      Context for metadata-action (mainly for overriding ref/sha). Set to "git" when code is checked out from
      a ref (e.g. tag created during workflow) that is different than the ref that triggered the workflow. 
      That ensures the sem-ver image tags are included when tagging the docker image.
    default: workflow
    required: false
  raw-tags:
    description: Extra raw tags (space delimited)
    default: ''
    required: false
outputs:
  tags:
    description: "Image Tags"
    value: ${{ steps.meta.outputs.tags }}
  imageid:
    description: "Image ID"
    value: ${{ steps.build_push.outputs.imageid }}
  digest:
    description: "Image digest"
    value: ${{ steps.build_push.outputs.digest }}
  metadata:
    description: "Labels and tags generated by docker metadata"
    value: ${{ steps.meta.outputs.json }}

runs:
  using: composite
  steps:
    - name: Set environment variables
      shell: bash
      run: |

        # Push tag has this context:
        #
        # github.ref: refs/tags/v1.2.3
        # github.head_ref: ""
        # github.ref_name: "v1.2.3"
        # github.ref_type: "tag"
      
        echo "GIT_BRANCH=$GIT_BRANCH" | tee -a $GITHUB_ENV
        echo "GITHUB_SHA_SHORT=${GITHUB_SHA:0:7}" | tee -a $GITHUB_ENV
        echo "GITHUB_PR_SHA_SHORT=${GITHUB_PR_SHA:0:7}" | tee -a $GITHUB_ENV
        echo "GHCR_IMAGE=${GHCR_IMAGE_MIXED,,}" | tee -a $GITHUB_ENV
      env:
        GHCR_IMAGE_MIXED: ${{ inputs.github-repo }}/${{ github.repository }}
        GITHUB_PR_SHA: ${{ github.event.pull_request.head.sha }}
        GIT_BRANCH: ${{ github.head_ref || github.ref_name }}

    #
    # Tags are defined based on workflow event (tag, push, pull_request, etc.)
    #
    # push semver tag (refs/tags/v1.2.3)
    #  - v1.2.3
    #  - v1.2
    #  - latest (unless suffix exists; v1.2.3-rc.1 will produce semver tag only)
    #
    # push:
    #  - REFNAME (everything after refs/heads, e.g. main)
    #
    # pull_request (refs/pull):
    #  - pr-PRNUM (mutable latest)
    #  - pr-PRNUM-PR_SHA_SHORT (PR commit)
    #
    # all:
    #  - sha-BUILD_SHA_SHORT (commit that triggered workflow and used for build)
    #
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        context: ${{ inputs.context }}
        images: |
          ${{ env.GHCR_IMAGE }}
        labels: ${{ inputs.labels }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=ref,event=pr,suffix=-${{ env.GITHUB_PR_SHA_SHORT }}
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,format=short,prefix=sha-
          ${{ inputs.raw-tags }}

    # Tag include image repository
    - name: Show docker meta
      shell: bash
      run: |
        echo -e "tags:\n${{ steps.meta.outputs.tags }}"
        echo -e "labels:\n${{ steps.meta.outputs.labels }}"

    - name: Set up QEMU for docker build push action
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to ghcr.io
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.github-repo }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Build and push
      id: build_push
      uses: docker/build-push-action@v4
      with:
        # docker image build . --file docker/Dockerfile
        context: .
        # Uncomment to support arm64 as well
        # platforms: linux/amd64,linux/arm64
        file: ${{ inputs.dockerfile }}
        # Push when: a) commit to target; b) PR labeled "preview"
        push: ${{ github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'preview') }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

# push false =>
#     {
#   "outputs": {
#     "metadata": "{}"
#   },
#   "outcome": "success",
#   "conclusion": "success"
# }

    - name: Dump outputs for debugging
      if: ${{ true }}
      shell: bash
      run: |
        echo "$OUTPUTS"
      env:
        OUTPUTS: ${{ toJson(steps.build_push) }}

    - name: Show build and push meta
      shell: bash
      run: |
        echo -e "image id:\n${{ steps.build_push.outputs.imageid }}"
        echo -e "image digest:\n${{ steps.build_push.outputs.digest }}"
        echo -e "metadata:\n${{ steps.build_push.outputs.metadata }}"


   
