apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otel-hello
commonLabels:
  app: otel-hello
resources:
- ../base
- serviceMonitor.yaml
- namespace.yaml

patches:
- path: deployment.yaml


images:
- name: ghcr.io/liam-murray-xealth/otel-hello:latest
  newTag: latest
