apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# So gets scraped by fluentbit
namespace: xealth
commonLabels:
  app: otel-hello
resources:
- ../base
- serviceMonitor.yaml
#- namespace.yaml

patches:
- path: deployment.yaml


images:
- name: ghcr.io/liam-murray-xealth/otel-nest-hello
  newTag: main
