apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-hello
  labels:
    app: otel-hello
    # label associated with prom operator
    release: prometheus
spec:
  selector:
    matchLabels:
      app: otel-hello
  # jobLabel: jobLabel
  endpoints:
  - port: metrics
    interval: 30s
  namespaceSelector:
    matchNames:
    - otel-hello
