name: Build
on:
  push:
    branches:
      - main
    # Don't ignore md files since we run markdownlint
    # paths-ignore:
    #   - '**/README.md'

  pull_request:
    types: [opened, synchronize, reopened]

env:
  AWS_REGION: us-west-2
  IAM_ROLE_PUBLISH_TECHDOCS:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      id-token: write
      packages: write
      contents: read
    steps:
      - name: Dump context for debugging
        run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies with audit
        run: |
          npm ci
          npm audit check --omit=dev --audit-level=high
          npm run lint
          npm run build

      - name: Run tests
        run: npm run test

      - name: Publish docs
        uses: ./.github/actions/publish-docs
        with:
          entity: default/Component/otel-nest-hello

      - name: Build and push docker
        uses: ./.github/actions/docker-build
        with:
          labels: |
            org.opencontainers.image.title=Otel Demo
            org.opencontainers.image.description=Nest.Js with OTEL and other random experimentation
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          DOCKER_BUILDKIT: 1
